### ISSUE TITLE
 Odoo v9 - SEPA export file #1 

### ISSUE THREAD

**Issue by dgouthiere** [unamur-dev/odoo-account#1]
Hello All, François, 
Installing and testing odoo v9 sepa_export-9.0.1.0 dowloaded from Odoo apps https://www.odoo.com/apps/modules/9.0/sepa_export/ 
I get the following error when clicking Expor to SEPA

Could you please advise me or fix the bug ? detail to reproduce the case is available in the attached document

Thank you,
David,

SEPA SCT error 1 - Exporting an XML SEPA file for credit transfer.docx

**Comment by fdegrave** [comment]
Thanks for the bug report ! This was indeed a bug that we just fixed in our last commit.

**Comment by dgouthiere** [comment]
Thanks for quick fix François, 
However issue is not entirely solved. I load the fix, restart server and now get  : object has no attribute 'wizard_action'
[SEPA SCT error 1 - Exporting an XML SEPA file for credit transfer v2.docx](https://github.com/unamur-dev/odoo-account/files/289568/SEPA.SCT.error.1.-.Exporting.an.XML.SEPA.file.for.credit.transfer.v2.docx)
see detail in attachment
Could you please  check it again or tell me what i am doing wrong ?
With kind regards,
David

**Comment by fdegrave** [comment]
Indeed! Sorry, it's now fixed -- hopefully nothing gets in the way from now on :-)

**Comment by dgouthiere** [comment]
Thank for so good reactivity ! i continue testing
David
